###
# 1. GET ALL ATTRACTIONS (200 OK)

### Get all attractions
GET localhost:8080/attractions

###
# 2. GET ATTRACTION BY NAME

### Get existing attraction (200 OK)
GET localhost:8080/attractions/Dolphin Show

### Get another existing attraction (200 OK)
GET localhost:8080/attractions/Cat Cafe

### Get non-existing attraction (404 NOT FOUND)
GET localhost:8080/attractions/Unknown

###
# 3. ADD NEW ATTRACTION

### Add valid attraction (201 CREATED)
POST localhost:8080/attractions/add
Content-Type: application/json

{
  "name": "Aquarium",
  "description": "A place with many underwater animals"
}

### Error: missing name (400 BAD REQUEST)
POST http://localhost:8080/attractions/add
Content-Type: application/json

{
  "description": "Missing name field"
}

### Error: missing description (400 BAD REQUEST)
POST localhost:8080/attractions/add
Content-Type: application/json

{
  "name": "Zoo"
}

### Error: empty fields (400 BAD REQUEST)
POST http://localhost:8080/attractions/add
Content-Type: application/json

{
  "name": "",
  "description": ""
}

### Error: duplicate name (400 BAD REQUEST)
POST localhost:8080/attractions/add
Content-Type: application/json

{
  "name": "Cat Cafe",
  "description": "Duplicate test"
}

###
# 4. UPDATE ATTRACTION

### Valid update: change name + description (200 OK)
POST localhost:8080/attractions/update
Content-Type: application/json

{
  "oldName": "Dolphin Show",
  "newName": "Dolphin Experience",
  "newDescription": "Some new Description"
}

### Valid update: only change description (200 OK)
POST localhost:8080/attractions/update
Content-Type: application/json

{
  "oldName": "Cat Cafe",
  "newName": "",
  "newDescription": "New description only"
}

### Valid update: only change name (200 OK)
POST localhost:8080/attractions/update
Content-Type: application/json

{
  "oldName": "Aquarium",
  "newName": "Ocean World",
  "newDescription": ""
}

### Error: oldName not found (404 NOT FOUND)
POST localhost:8080/attractions/update
Content-Type: application/json

{
  "oldName": "Unknown",
  "newName": "newName",
  "newDescription": "NewDescription"
}

### Valid: no newName field (200 OK) only update description
POST localhost:8080/attractions/update
Content-Type: application/json

{
  "oldName": "Dolphin Experience",
  "newDescription": "New description null newName field"
}



###
# 5. DELETE ATTRACTION

### Valid delete (200 OK)
POST http://localhost:8080/attractions/delete/Cat Cafe

### Delete non-existing attraction (404 NOT FOUND)
POST localhost:8080/Unknown

### Empty field: Same error as above (404 NOT FOUND)
POST localhost:8080/attractions/delete/